import test from "node:test";
import assert from "node:assert/strict";
import { parseDeviceObservations } from "./device-observations.mjs";
const identity = { firmwareCommit: "a".repeat(40), appElfSha256: "b".repeat(64) };
function marker(patch = {}) {
  const values = { schema: "v1", slot: "first_bootstrap", category: "bootstrap_diagnostic", record_kind: "startup_progress", outcome: "completed", stage: "completed", start_ms: 90, end_ms: 1990, record_bytes: 92, queued_bytes: 92, queue_calls: 1, queue_positive: 1, queue_zero: 0, last_queue_return: 92, drain_calls: 2, drain_timeout: 1, drain_success: 1, drain_other: 0, first_drain_ms: 90, last_drain_ms: 1990, max_drain_ms: 1890, last_drain_return: 0, actual_failures: 0, replay_attempts: 0, replay_completed: 0, flags: 0, redacted: true, ...patch };
  return "usb_tx_observation " + Object.entries(values).map(([key, value]) => `${key}=${value}`).join(" ");
}
function log(records, suffix = "") { return [`usb_runtime_identity schema=v1 firmware_commit=${identity.firmwareCommit} app_elf_sha256=${identity.appElfSha256} redacted=true`, "usb_reboot_discriminator schema=v1 boot_ordinal=18 reset_reason=software_cpu uptime_ms=100 redacted=true", ...records, "usb_startup schema=v1 stage=runtime_ready state=complete first_failure=none uptime_ms=3000 redacted=true", "usb_reboot_discriminator schema=v1 boot_ordinal=18 reset_reason=software_cpu uptime_ms=4000 redacted=true", ""].join("\n") + suffix; }
const parse = records => parseDeviceObservations(log(records), identity);
test("completed bootstrap is a measurement, not delivery or qualification", () => { const result = parse([marker()]); assert.equal(result.complete, true); assert.equal(result.firstBootstrap.record_kind, "startup_progress"); assert.equal(result.bootOrdinal, 18); assert.equal(Object.hasOwn(result, "hardware_qualified"), false); });
test("failed drain observed beyond deadline remains valid failure evidence", () => { const failure = { outcome: "failed", stage: "flush_timeout", end_ms: 2150, last_drain_ms: 2150, max_drain_ms: 2000, drain_success: 0, drain_timeout: 2, last_drain_return: 263, actual_failures: 1 }; const result = parse([marker(failure), marker({ ...failure, slot: "first_failure", replay_attempts: 1, replay_completed: 1 })]); assert.equal(result.complete, true); assert.equal(result.firstFailure.end_ms, 2150); });
test("cancellation before first queue call is representable", () => { const failure = { outcome: "failed", stage: "cancelled", end_ms: 90, queued_bytes: 0, queue_calls: 0, queue_positive: 0, last_queue_return: 0, drain_calls: 0, drain_timeout: 0, drain_success: 0, first_drain_ms: 0, last_drain_ms: 0, max_drain_ms: 0, actual_failures: 1 }; assert.equal(parse([marker(failure), marker({ ...failure, slot: "first_failure" })]).complete, true); });
for (const [name, patch] of Object.entries({ late_success: { end_ms: 2091 }, impossible_counts: { queue_calls: 0 }, unknown_kind: { record_kind: "private" }, secret_field: { payload: "secret" }, unknown_flag: { flags: 8 }, overflow: { flags: 1 }, precision: { end_ms: "9007199254740993" }, failure_missing: { actual_failures: 1 }, replay_excess: { replay_completed: 1 } })) test(`rejects ${name}`, () => { assert.equal(parse([marker(patch)]).complete, false); });
test("retained first observation cannot be replaced by later success", () => { assert.ok(parse([marker(), marker({ end_ms: 1991, last_drain_ms: 1991 })]).issues.includes("device_retained_observation_changed")); });
test("replay count regression cannot be hidden", () => { assert.ok(parse([marker({ replay_attempts: 2 }), marker({ replay_attempts: 1 })]).issues.includes("device_counter_regression")); });
test("mixed identity and rebooted streams fail binding", () => { const text = log([marker()]).replace("boot_ordinal=18", "boot_ordinal=19").replace(identity.appElfSha256, "c".repeat(64)); const result = parseDeviceObservations(text, identity); assert.equal(result.complete, false); assert.ok(result.issues.includes("device_identity")); assert.ok(result.issues.includes("stable_boot_missing")); });
test("incomplete trailing marker is retained as truncation without parsing private text", () => { const result = parseDeviceObservations(log([marker()], "usb_tx_observation secret=private"), identity); assert.equal(result.truncatedTail, true); assert.equal(JSON.stringify(result).includes("private"), false); });
test("92 bytes never infer a bootstrap category", () => { const result = parse([marker({ category: "control_reply" })]); assert.ok(result.issues.includes("device_bootstrap_category")); });

test("descheduling before first queue preserves timeout evidence", () => { const failure = { outcome: "failed", stage: "write_timeout", end_ms: 2100, queued_bytes: 0, queue_calls: 0, queue_positive: 0, last_queue_return: 0, drain_calls: 0, drain_timeout: 0, drain_success: 0, first_drain_ms: 0, last_drain_ms: 0, max_drain_ms: 0, actual_failures: 1 }; assert.equal(parse([marker(failure), marker({ ...failure, slot: "first_failure" })]).complete, true); });
test("failed bootstrap cannot claim zero failures", () => { assert.equal(parse([marker({outcome: "failed", stage: "flush_timeout"})]).complete, false); });
test("discarded boot boundary cannot hide a new boot", () => { const result = parseDeviceObservations(log([marker()], "usb_reboot_discriminator schema=v1 boot_ordinal=19"), identity); assert.equal(result.complete, false); assert.ok(result.issues.includes("truncated_device_record")); });
