//! Copied from bitaxe-turnstile-system `conformance/bwg-worker-controller-0.4/soak-allowance-vectors.json`,
//! generated by its `scripts/generate-soak-allowance-fixtures.ts` with the public RFC 8032 test key.
use super::*;
use serde_json::Value;
fn fixture() -> Value {
    serde_json::from_str(include_str!("gate-soak.json")).expect("public soak fixture")
}
fn verifier(f: &Value) -> WorkLeaseAuthorizationVerifier<MemorySequenceStore> {
    let mut trust: Value = serde_json::from_str(TRUST).expect("fixture");
    trust["workLeaseAuthority"] = f["trust"].clone();
    WorkLeaseAuthorizationVerifier::new(
        WorkLeaseAuthorityTrust::from_deployment_json(&trust.to_string()).expect("trust"),
        MemorySequenceStore::default(),
    )
}
fn context(vector: &Value) -> WorkerLeaseAuthorizationContext {
    WorkerLeaseAuthorizationContext::parse(
        vector["input"]["controlSessionBindingSha256"]
            .as_str()
            .expect("binding"),
    )
    .expect("context")
}
#[test]
fn gate_signed_soak_grants_verify_in_rust_with_their_profiles() {
    // Arrange
    let f = fixture();
    let mut v = verifier(&f);
    for vector in f["vectors"].as_array().expect("vectors") {
        let grant: WorkerLeaseGrant =
            serde_json::from_value(vector["grant"].clone()).expect("grant");
        // Act / Assert
        assert_eq!(v.verify_start(&grant, &context(vector)), Ok(()));
        assert_eq!(
            serde_json::to_value(grant.hardware_profile()).expect("profile"),
            vector["hardwareProfile"]
        );
    }
}
#[test]
fn changing_the_signed_profile_or_allowance_invalidates_authorization() {
    // Arrange
    let f = fixture();
    let vector = &f["vectors"][0];
    for (pointer, value) in [
        ("/hardwareProfile", serde_json::json!("conservative")),
        ("/soakAllowance/ordinal", serde_json::json!(2)),
        (
            "/soakAllowance/id",
            serde_json::json!("AQEBAQEBAQEBAQEBAQEBAQ"),
        ),
    ] {
        let mut grant = vector["grant"].clone();
        *grant.pointer_mut(pointer).expect("field") = value;
        let grant: WorkerLeaseGrant = serde_json::from_value(grant).expect("grant");
        // Act / Assert
        assert!(verifier(&f).verify_start(&grant, &context(vector)).is_err());
    }
}
