use super::*;

pub(super) fn rows() -> Vec<SettingSchema> {
    vec![
        SettingSchema {
            key: key("asicfrequency_f"),
            stored_type: StoredType::FloatString,
            default_value: Some(SettingDefault::Float(485.0)),
            rest_name: Some(rest("frequency")),
            min: Some(1),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("asicvoltage"),
            stored_type: StoredType::U16,
            default_value: Some(SettingDefault::U16(1200)),
            rest_name: Some(rest("coreVoltage")),
            min: Some(1),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("oc_enabled"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: Some(rest("overclockEnabled")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("display"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("display")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("rotation"),
            stored_type: StoredType::U16,
            default_value: Some(SettingDefault::U16(0)),
            rest_name: Some(rest("rotation")),
            min: Some(0),
            max: Some(270),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("invertscreen"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: Some(rest("invertscreen")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("displayOffset"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("displayOffset")),
            min: Some(0),
            max: Some(255),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("displayTimeout"),
            stored_type: StoredType::I32,
            default_value: Some(SettingDefault::I32(-1)),
            rest_name: Some(rest("displayTimeout")),
            min: Some(-1),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("autofanspeed"),
            stored_type: StoredType::BoolAsU16,
            default_value: Some(SettingDefault::Bool(true)),
            rest_name: Some(rest("autofanspeed")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("manualfanspeed"),
            stored_type: StoredType::U16,
            default_value: Some(SettingDefault::U16(100)),
            rest_name: Some(rest("manualFanSpeed")),
            min: Some(0),
            max: Some(100),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("minfanspeed"),
            stored_type: StoredType::U16,
            default_value: Some(SettingDefault::U16(25)),
            rest_name: Some(rest("minFanSpeed")),
            min: Some(0),
            max: Some(99),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("temptarget"),
            stored_type: StoredType::U16,
            default_value: Some(SettingDefault::U16(60)),
            rest_name: Some(rest("temptarget")),
            min: Some(35),
            max: Some(66),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("overheat_mode"),
            stored_type: StoredType::BoolAsU16,
            default_value: Some(SettingDefault::Bool(false)),
            rest_name: Some(rest("overheat_mode")),
            min: Some(0),
            max: Some(0),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
    ]
}
