use super::*;

pub(super) fn rows() -> Vec<SettingSchema> {
    vec![
        SettingSchema {
            key: key("fbstratumprot"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("SV1")),
            rest_name: Some(rest("fallbackStratumProtocol")),
            min: Some(3),
            max: Some(3),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumurl"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("fallbackStratumURL")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumport"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("fallbackStratumPort")),
            min: Some(0),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumuser"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("fallbackStratumUser")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumpass"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("fallbackStratumPassword")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumdiff"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("fallbackStratumSuggestedDifficulty")),
            min: Some(0),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumfbxnsub"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: Some(rest("fallbackStratumExtranonceSubscribe")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumtls"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("fallbackStratumTLS")),
            min: Some(0),
            max: Some(3),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumcert"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("fallbackStratumCert")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbsv2chantype"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("extended")),
            rest_name: Some(rest("fallbackStratumV2ChannelType")),
            min: Some(8),
            max: Some(8),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbsv2authpubk"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("")),
            rest_name: Some(rest("fallbackStratumV2AuthorityPubkey")),
            min: Some(0),
            max: Some(52),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("fbstratumdecode"),
            stored_type: StoredType::BoolAsU16,
            default_value: Some(SettingDefault::Bool(true)),
            rest_name: Some(rest("fallbackStratumDecodeCoinbase")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("usefbstartum"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: Some(rest("useFallbackStratum")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
    ]
}
