use super::*;

pub(super) fn rows() -> Vec<SettingSchema> {
    vec![
        SettingSchema {
            key: key("statsFrequency"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("statsFrequency")),
            min: Some(0),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("bestdiff"),
            stored_type: StoredType::U64,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("selftest"),
            stored_type: StoredType::BoolAsU16,
            default_value: Some(SettingDefault::Bool(true)),
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("swarmconfig"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("themescheme"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str(DEFAULT_THEME_COLOR_SCHEME)),
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("themecolors"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str(DEFAULT_THEME_ACCENT_COLORS_JSON)),
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("scoreboard"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: Some(20),
            provenance: "reference/esp-miner/main/tasks/scoreboard.h MAX_SCOREBOARD",
        },
    ]
}
