use super::*;

pub(super) fn rows() -> Vec<SettingSchema> {
    vec![
        SettingSchema {
            key: key("boardversion"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("000")),
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("devicemodel"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("unknown")),
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("asicmodel"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("unknown")),
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("plug_sense"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("asic_enable"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("EMC2101"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("EMC2103"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("EMC2302"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
    ]
}
