use super::*;

pub(super) fn rows() -> Vec<SettingSchema> {
    vec![
        SettingSchema {
            key: key("stratumprot"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("SV1")),
            rest_name: Some(rest("stratumProtocol")),
            min: Some(3),
            max: Some(3),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumurl"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("stratumURL")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumport"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("stratumPort")),
            min: Some(0),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumuser"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("stratumUser")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumpass"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("stratumPassword")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumdiff"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("stratumSuggestedDifficulty")),
            min: Some(0),
            max: Some(65535),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumxnsub"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: Some(rest("stratumExtranonceSubscribe")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumtls"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: Some(rest("stratumTLS")),
            min: Some(0),
            max: Some(3),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumcert"),
            stored_type: StoredType::Str,
            default_value: None,
            rest_name: Some(rest("stratumCert")),
            min: Some(0),
            max: Some(3999),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("sv2chantype"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("extended")),
            rest_name: Some(rest("stratumV2ChannelType")),
            min: Some(8),
            max: Some(8),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("sv2authpubkey"),
            stored_type: StoredType::Str,
            default_value: Some(SettingDefault::Str("")),
            rest_name: Some(rest("stratumV2AuthorityPubkey")),
            min: Some(0),
            max: Some(52),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("stratumdecode"),
            stored_type: StoredType::BoolAsU16,
            default_value: Some(SettingDefault::Bool(true)),
            rest_name: Some(rest("stratumDecodeCoinbase")),
            min: Some(0),
            max: Some(1),
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
    ]
}
