use super::*;

pub(super) fn rows() -> Vec<SettingSchema> {
    vec![
        SettingSchema {
            key: key("emc_int_temp"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("emc_ideality_f"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("emc_beta_comp"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("temp_offset"),
            stored_type: StoredType::I32,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("DS4432U"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("INA260"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("TPS546"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("TMP1075"),
            stored_type: StoredType::BoolAsU16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
        SettingSchema {
            key: key("power_cons_tgt"),
            stored_type: StoredType::U16,
            default_value: None,
            rest_name: None,
            min: None,
            max: None,
            array_size: None,
            provenance: SETTINGS_PROVENANCE,
        },
    ]
}
